site_name: DHARPA - Workflows requirements
theme:
  name: material
markdown_extensions:
  - tables
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
nav:
  - 'Network Analysis':
    - 'Directed weighted graph analysis': 'na-directed-weighted.md'
    - 'Undirected bipartite graph analysis': 'na-bipartite.md'
  - 'Templates':
    - 'Workflow': 'blank-workflow.md'