name: "Build and deploy documentation pages"

on: [push]

  jobs:

  build-docs:
    name: build documentation
    runs-on: ubuntu-latest
    needs:
      - test-linux
      - mypy-linux
      - flake8-linux
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: pip cache
        id: pip-cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.*') }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install requirements
      - run: pip install -r requirements.txt
      - name: install insiders version of mkdocs-material
        run: pip install --upgrade --force-reinstall "git+https://${{ secrets.MKDOCS_MATERIAL_PULL_TOKEN }}@github.com/DHARPA-Project/mkdocs-material-insiders.git"
      - run: git config --global user.email "mariella.decrouychanel@uni.lu"
      - run: git config --global user.name "Mariella de Crouy Chanel"
      - name: create latest documentation
        if: ${{ ( github.ref == 'refs/heads/develop') }}
        run: FAIL_DOC_BUILD_ON_ERROR=true mike deploy --push latest && mike set-default --push latest
      - name: extract tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: create stable documentation
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: FAIL_DOC_BUILD_ON_ERROR=true mike deploy --push --update-alias --title "v ${RELEASE_VERSION}" "${RELEASE_VERSION}" stable
